package controller

// The RBAC of rung observe, generated by `make manifests` into config/rbac/observe/role.yaml
// and held equal to test/golden/rbac-observe.yaml and the envelope by rbac_golden_test.go.
// Every rule is get/list/watch except the two writes of the rung: the Estate's status and
// Events on it. No Secret, no ConfigMap, no exec, nothing in `*` form, nothing cluster-wide
// but Nodes.
//
// Namespaces: tq-operator is the operator's own; operations and tequila are the default
// platform and services namespaces — an estate's render produces the same Roles in the
// environment's actual namespaces. Flux's objects (every Kustomization, the flux-system
// GitRepository, the FluxInstance) live in flux-system in every render, so the Flux Role is
// bound there.

// The one cluster-scoped read: Nodes (versions, architectures, count — never a name in a report).
// +kubebuilder:rbac:groups="",resources=nodes,verbs=get;list;watch,roleName=tq-operator-observe-cluster

// The operator's own namespace: its resources, its record.
// +kubebuilder:rbac:groups=estate.tequila.dev,resources=estates,verbs=get;list;watch,namespace=tq-operator,roleName=tq-operator-self
// +kubebuilder:rbac:groups=estate.tequila.dev,resources=estates/status,verbs=get;update;patch,namespace=tq-operator,roleName=tq-operator-self
// +kubebuilder:rbac:groups="",resources=events,verbs=create;patch,namespace=tq-operator,roleName=tq-operator-self

// The platform namespace.
// +kubebuilder:rbac:groups=apps,resources=deployments;replicasets,verbs=get;list;watch,namespace=operations,roleName=tq-operator-observe
// +kubebuilder:rbac:groups="",resources=pods,verbs=get;list;watch,namespace=operations,roleName=tq-operator-observe
// +kubebuilder:rbac:groups=external-secrets.io,resources=externalsecrets,verbs=get;list;watch,namespace=operations,roleName=tq-operator-observe

// The services namespace.
// +kubebuilder:rbac:groups=apps,resources=deployments;replicasets,verbs=get;list;watch,namespace=tequila,roleName=tq-operator-observe
// +kubebuilder:rbac:groups="",resources=pods,verbs=get;list;watch,namespace=tequila,roleName=tq-operator-observe
// +kubebuilder:rbac:groups=external-secrets.io,resources=externalsecrets,verbs=get;list;watch,namespace=tequila,roleName=tq-operator-observe

// Flux's namespace.
// +kubebuilder:rbac:groups=kustomize.toolkit.fluxcd.io,resources=kustomizations,verbs=get;list;watch,namespace=flux-system,roleName=tq-operator-observe-flux
// +kubebuilder:rbac:groups=source.toolkit.fluxcd.io,resources=gitrepositories;ocirepositories,verbs=get;list;watch,namespace=flux-system,roleName=tq-operator-observe-flux
// +kubebuilder:rbac:groups=fluxcd.controlplane.io,resources=fluxinstances,verbs=get;list;watch,namespace=flux-system,roleName=tq-operator-observe-flux
